import 'dart:convert';

import 'package:flutter/material.dart';

import 'package:http/http.dart' as http;
import 'newsClass.dart';

//This page displays the most recent news reports from the https://newsapi.org/v2/top-headlines?country=us&apiKey=7e7fa6d1f30f427695b01c1ac3b6f018 uses the class 
// to help display the most recent articles



class Search extends StatefulWidget {
  @override
  _SearchState createState() => _SearchState();
}

class _SearchState extends State<Search> {
  Map worldData;
  Autogenerated autogenerated;
  Articles articles;
  String a;
  String b;
  String c;
  String d;
  String e;
  String f;
  fetchWorldWideData()async{
    http.Response response = await http.get('https://newsapi.org/v2/top-headlines?country=us&apiKey=7e7fa6d1f30f427695b01c1ac3b6f018');
    setState(() {
      worldData = json.decode(response.body);
      Autogenerated autogenerated = new Autogenerated.fromJson(worldData);
      Articles articles = new Articles.fromJson(worldData);
      a = autogenerated.articles[0].title.toString();
      b = autogenerated.articles[1].title.toString();
      c = autogenerated.articles[2].title.toString();
      d = autogenerated.articles[3].title.toString();
      e = autogenerated.articles[4].title.toString();
      f = autogenerated.articles[4].title.toString();
    });

    
  }

@override
void initState() { 
  fetchWorldWideData();
  super.initState();
  
}
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: false,
        title: Text(
          'Covid-19 Tracker',
          style: TextStyle(color: Colors.black),
        ),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Padding(padding: const EdgeInsets.symmetric(vertical: 5.0),),
          Container(
            height: 100,
            alignment: Alignment.center,
            padding: EdgeInsets.all(10),
            color: Colors.purple[900],
            child: Text(
              'Latest News:  $a',
              style: TextStyle(
                color: Colors.orange[800],
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            
          ),
          Container(
            height: 100,
            alignment: Alignment.center,
            padding: EdgeInsets.all(10),
            color: Colors.purple[900],
            child: Text(
              'Latest News:  $b',
              style: TextStyle(
                color: Colors.orange[800],
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),

          Padding(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            
          ),
          Container(
            height: 100,
            alignment: Alignment.center,
            padding: EdgeInsets.all(10),
            color: Colors.purple[900],
            child: Text(
              'Latest News:  $c',
              style: TextStyle(
                color: Colors.orange[800],
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),

          Padding(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            
          ),
          Container(
            height: 100,
            alignment: Alignment.center,
            padding: EdgeInsets.all(10),
            color: Colors.purple[900],
            child: Text(
              'Latest News:  $d',
              style: TextStyle(
                color: Colors.orange[800],
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),

          Padding(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            
          ),
          Container(
            height: 100,
            alignment: Alignment.center,
            padding: EdgeInsets.all(10),
            color: Colors.purple[900],
            child: Text(
              'Latest News:  $e',
              style: TextStyle(
                color: Colors.orange[800],
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),

          Padding(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            
          ),
          Container(
            height: 100,
            alignment: Alignment.center,
            padding: EdgeInsets.all(10),
            color: Colors.purple[900],
            child: Text(
              'Latest News:  $f',
              style: TextStyle(
                color: Colors.orange[800],
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),


        ],
      ),
      );
  }
}

class UserResult extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold();
  }
}
