class Autogenerated {
  String state;
  int positive;
  int positiveScore;
  int negativeScore;
  int negativeRegularScore;
  int commercialScore;
  String grade;
  int score;
  String notes;
  String dataQualityGrade;
  int negative;
  int pending;
  Null hospitalizedCurrently;
  int hospitalizedCumulative;
  Null inIcuCurrently;
  Null inIcuCumulative;
  Null onVentilatorCurrently;
  Null onVentilatorCumulative;
  Null recovered;
  String lastUpdateEt;
  String checkTimeEt;
  int death;
  int hospitalized;
  int total;
  int totalTestResults;
  int posNeg;
  String fips;
  String dateModified;
  String dateChecked;
  String hash;

  Autogenerated(
      {this.state,
      this.positive,
      this.positiveScore,
      this.negativeScore,
      this.negativeRegularScore,
      this.commercialScore,
      this.grade,
      this.score,
      this.notes,
      this.dataQualityGrade,
      this.negative,
      this.pending,
      this.hospitalizedCurrently,
      this.hospitalizedCumulative,
      this.inIcuCurrently,
      this.inIcuCumulative,
      this.onVentilatorCurrently,
      this.onVentilatorCumulative,
      this.recovered,
      this.lastUpdateEt,
      this.checkTimeEt,
      this.death,
      this.hospitalized,
      this.total,
      this.totalTestResults,
      this.posNeg,
      this.fips,
      this.dateModified,
      this.dateChecked,
      this.hash});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    state = json['state'];
    positive = json['positive'];
    positiveScore = json['positiveScore'];
    negativeScore = json['negativeScore'];
    negativeRegularScore = json['negativeRegularScore'];
    commercialScore = json['commercialScore'];
    grade = json['grade'];
    score = json['score'];
    notes = json['notes'];
    dataQualityGrade = json['dataQualityGrade'];
    negative = json['negative'];
    pending = json['pending'];
    hospitalizedCurrently = json['hospitalizedCurrently'];
    hospitalizedCumulative = json['hospitalizedCumulative'];
    inIcuCurrently = json['inIcuCurrently'];
    inIcuCumulative = json['inIcuCumulative'];
    onVentilatorCurrently = json['onVentilatorCurrently'];
    onVentilatorCumulative = json['onVentilatorCumulative'];
    recovered = json['recovered'];
    lastUpdateEt = json['lastUpdateEt'];
    checkTimeEt = json['checkTimeEt'];
    death = json['death'];
    hospitalized = json['hospitalized'];
    total = json['total'];
    totalTestResults = json['totalTestResults'];
    posNeg = json['posNeg'];
    fips = json['fips'];
    dateModified = json['dateModified'];
    dateChecked = json['dateChecked'];
    hash = json['hash'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['state'] = this.state;
    data['positive'] = this.positive;
    data['positiveScore'] = this.positiveScore;
    data['negativeScore'] = this.negativeScore;
    data['negativeRegularScore'] = this.negativeRegularScore;
    data['commercialScore'] = this.commercialScore;
    data['grade'] = this.grade;
    data['score'] = this.score;
    data['notes'] = this.notes;
    data['dataQualityGrade'] = this.dataQualityGrade;
    data['negative'] = this.negative;
    data['pending'] = this.pending;
    data['hospitalizedCurrently'] = this.hospitalizedCurrently;
    data['hospitalizedCumulative'] = this.hospitalizedCumulative;
    data['inIcuCurrently'] = this.inIcuCurrently;
    data['inIcuCumulative'] = this.inIcuCumulative;
    data['onVentilatorCurrently'] = this.onVentilatorCurrently;
    data['onVentilatorCumulative'] = this.onVentilatorCumulative;
    data['recovered'] = this.recovered;
    data['lastUpdateEt'] = this.lastUpdateEt;
    data['checkTimeEt'] = this.checkTimeEt;
    data['death'] = this.death;
    data['hospitalized'] = this.hospitalized;
    data['total'] = this.total;
    data['totalTestResults'] = this.totalTestResults;
    data['posNeg'] = this.posNeg;
    data['fips'] = this.fips;
    data['dateModified'] = this.dateModified;
    data['dateChecked'] = this.dateChecked;
    data['hash'] = this.hash;
    return data;
  }
}
